# Top-level configuration
name = "nicolai-dev-frontend"
compatibility_date = "2025-04-17"

route = { pattern = "nicolai.dev", custom_domain = true }

workers_dev = false
preview_urls = false

assets = { directory = "./build" }

[build]
command = "pnpm run build"
