# Top-level configuration
name = "nicolai-dev-backend"
main = "./src/index.ts"
compatibility_date = "2025-04-17"

route = "nicolai.dev/api/*"
workers_dev = false
preview_urls = false

observability.enabled = true

vars = { ENVIRONMENT = "dev" }
env.production.vars.ENVIRONMENT = "production"
